name: IKIGAI - Worth Living For
favicon: null
layout_spectrum: 0.25294914189726114
typography_spectrum: 0.8339711390435696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5fcfc'
    - '#627cb0'
    - '#9acce1'
    - '#0c1123'
    - '#913e2c'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.7920866555068642
purpose: []
